name: Cypress Tests

on: [push, pull_request]

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Start server
        run: npm start &

      - name: Run Cypress
        uses: cypress-io/github-action@v6
        with:
          browser: chrome
          start: npm start
